/* SPDX-License-Identifier: BSD-2-Clause */
/* LiteOS feature configuration for the upstream NASM 3.02 sources. */

#ifndef LITEOS_NASM_CONFIG_H
#define LITEOS_NASM_CONFIG_H 1

#include "../../../third_party/nasm/config/unconfig.h"

#define PACKAGE_NAME "nasm"
#define PACKAGE_TARNAME "nasm"
#define PACKAGE_VERSION "3.02"
#define PACKAGE_STRING "nasm 3.02"
#define PACKAGE_URL "https://www.nasm.us/"
#define PACKAGE_BUGREPORT "https://bugs.nasm.us/"

#define STDC_HEADERS 1
#define WORDS_LITTLEENDIAN 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_LIMITS_H 1
#define HAVE_WCHAR_H 1

#define HAVE_DECL_STRCASECMP 1
#define HAVE_DECL_STRNCASECMP 1
#define HAVE_DECL_STRLCPY 1
#define HAVE_DECL_STRNLEN 1
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_STRLCPY 1

#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_STRUCT_STAT 1
#define HAVE_STAT 1
#define HAVE_FSTAT 1
#define HAVE_FILENO 1
#define HAVE_FSEEKO 1
#define HAVE_FTRUNCATE 1
#define HAVE_S_ISREG 1
#define HAVE_ACCESS 1
#define HAVE_MMAP 1
#define HAVE_SYSCONF 1
#define HAVE_GETPAGESIZE 1
#define HAVE_PATHCONF 1
#define HAVE_REALPATH 1

#define HAVE_TYPEOF 1
#define HAVE_UINTMAX_T 1
#define HAVE_UINTPTR_T 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_VARIADIC_MACROS 1
#define HAVE_STDC_INLINE 1
#define HAVE___BOOL 1
#define HAVE___BUILTIN_CLZ 1
#define HAVE___BUILTIN_CLZLL 1
#define HAVE___BUILTIN_CHOOSE_EXPR 1
#define HAVE___BUILTIN_CONSTANT_P 1
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___BUILTIN_PREFETCH 1
#define HAVE___BUILTIN_UNREACHABLE 1

#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_MEMPCPY 1
#define HAVE_ISASCII 1
#define HAVE_ISCNTRL 1

#define HAVE_FUNC_ATTRIBUTE_1_ALLOC_SIZE 1
#define HAVE_FUNC_ATTRIBUTE_2_ALLOC_SIZE 1
#define HAVE_FUNC_ATTRIBUTE_3_FORMAT 1
#define HAVE_FUNC_ATTRIBUTE_COLD 1
#define HAVE_FUNC_ATTRIBUTE_CONST 1
#define HAVE_FUNC_ATTRIBUTE_ERROR 1
#define HAVE_FUNC_ATTRIBUTE_MALLOC 1
#define HAVE_FUNC_ATTRIBUTE_NORETURN 1
#define HAVE_FUNC_ATTRIBUTE_PURE 1
#define HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL 1
#define HAVE_FUNC_ATTRIBUTE_SENTINEL 1
#define HAVE_FUNC_ATTRIBUTE_UNUSED 1
#define HAVE_FUNC_NAME 1

#endif /* LITEOS_NASM_CONFIG_H */
